tls:
  certificates:
    - certFile: /etc/traefik/certs/server/server.pem
      keyFile: /etc/traefik/certs/server/server.key
  options:
    client-auth:
      clientAuth:
        caFiles:
          - /etc/traefik/certs/client/rootCA2.pem
          - /etc/traefik/certs/client/inCA2.pem
        clientAuthType: RequireAndVerifyClientCert
http:
  serversTransports:
    mytransport:
      insecureSkipVerify: true
      # certificates:
      #   - certFile: /etc/traefik/certs/server/server.pem
      #     keyFile: /etc/traefik/certs/server/server.key
      # rootCAs:
      #   - /etc/traefik/certs/server/rootCA1.pem
      #   - /etc/traefik/certs/server/inCA1.pem
      #   - /etc/traefik/certs/client/rootCA2.pem
      #   - /etc/traefik/certs/client/inCA2.pem
  middlewares:
    test-passtlsclientcert:
      passTLSClientCert:
        pem: true
  routers:
    traefik:
      rule: "Host(`traefik.aimerzarashi.com`)"
      service: api@internal
      # tls: {}
      tls:
        options: client-auth@file
    whoami:
      rule: "Host(`whoami.aimerzarashi.com`)"
      service: whoami
      tls: {}
      # tls:
      #   options: client-auth@file
    web:
      rule: "Host(`web.aimerzarashi.com`)"
      service: web
      tls: {}
    idp:
      entryPoints:
        - "websecure"
      rule: "Host(`idp.aimerzarashi.com`)"
      service: idp
      tls: {}
      # tls:
      #   options: client-auth@file
      # middlewares: test-passtlsclientcert
    smtp:
      rule: "Host(`smtp.aimerzarashi.com`)"
      service: smtp
      tls: {}
    prometheus:
      rule: "Host(`prometheus.aimerzarashi.com`)"
      service: prometheus
      tls: {}
    grafana:
      rule: "Host(`grafana.aimerzarashi.com`)"
      service: grafana
      tls: {}
  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami:80
    web:
      loadBalancer:
        sticky:
          cookie: {}
        servers:
          - url: http://web:3000
    idp:
      loadBalancer:
        sticky:
          cookie: {}
        serversTransport: mytransport
        servers:
          - url: https://idp:8443
    smtp:
      loadBalancer:
        servers:
          - url: http://smtp:8025
    prometheus:
      loadBalancer:
        servers:
          - url: http://prometheus:9090
    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000
